package com.camp.block;
 
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.init.Items;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;

import com.camp.biome.features.NCLeaf;
import com.camp.biome.features.NCLog;
import com.camp.creativetabs.CreativeTabsManager;
import com.camp.item.ItemLeafBlocks;
import com.camp.item.ItemLogBlocks;
import com.camp.item.ItemManager;
import com.camp.lib.StringLibrary;

import cpw.mods.fml.common.registry.GameRegistry;
 
public class BlockManager {
 
    public static void mainRegistry() {
        initializeBlock();
        registerBlock();
    }
 
    public static Block customBlock;
    public static Block blockLog;
    public static Block sapphireChest;
    public static Block blockLeaf;
    public static Block multiBlock;
    public static Block blockAlabasterOvenIdle;
	public static Block blockAlabasterOvenActive;
	public static final int guiIDAlabasterOven = 0;
    public static Block testPortal;
    public static Block rubyBlock;
    public static Block amethystBlock;
    public static Block aquamarineBlock;
    public static Block citrineBlock;
    public static Block cobaltBlock;
    public static Block fireopalCrystalBlock;
    public static Block jetBlock;
    public static Block peridonBlock;
    public static Block roseQuartzBlock;
    public static Block sapphireBlock;
    public static Block siamBlock;
    public static Block topazBlock;
    public static Block tutorial_ore;
    public static Block endCoal;
    public static Block endDiamond;
    public static Block endIron;
    public static Block endEmerald;
    public static Block endGold;
    public static Block endRuby;
    public static Block endLapis;
    public static Block endRedstone;
    public static Block endQuartz;
    public static Block endAmethyst;
    public static Block endAquamarine;
    public static Block endCitrine;
    public static Block endCobalt;
    public static Block endFireopalCrystal;
    public static Block endJet;
    public static Block endPeridon;
    public static Block endRoseQuartz;
    public static Block endSapphire;
    public static Block endSiam;
    public static Block endTopaz;
    public static Block netherCoal;
    public static Block netherDiamond;
    public static Block netherIron;
    public static Block netherEmerald;
    public static Block netherGold;
    public static Block netherRuby;
    public static Block netherLapis;
    public static Block netherRedstone;
    public static Block netherAmethyst;
    public static Block netherAquamarine;
    public static Block netherCitrine;
    public static Block netherCobalt;
    public static Block netherFireopalCrystal;
    public static Block netherJet;
    public static Block netherPeridon;
    public static Block netherRoseQuartz;
    public static Block netherSapphire;
    public static Block netherSiam;
    public static Block netherTopaz;
   // public static Block 
    public static Block overworldQuartz;
    public static Block overworldAmethyst;
    public static Block overworldAquamarine;
    public static Block overworldCitrine;
    public static Block overworldCobalt;
    public static Block overworldFireopalCrystal;
    public static Block overworldJet;
    public static Block overworldPeridon;
    public static Block overworldRoseQuartz;
    public static Block overworldSapphire;
    public static Block overworldSiam;
    public static Block overworldTopaz;
    //public static Block customFarmland;
    public static Block customBlockCrops;
 
    public static void initializeBlock() {
    	rubyBlock = new RubyBlock(Material.iron).setBlockName("RubyBlock")/*.setBlockTextureName(StringLibrary.MODID + ":ruby_block")*/.setCreativeTab(CreativeTabsManager.tabBlock);
    	amethystBlock = new AmethystBlock(Material.iron).setBlockName("amethystBlock")/*.setBlockTextureName(StringLibrary.MODID + ":amethyst_block")*/.setCreativeTab(CreativeTabsManager.tabBlock);
    	aquamarineBlock = new AquamarineBlock(Material.iron).setBlockName("aquamarineBlock")/*.setBlockTextureName(StringLibrary.MODID + ":aquamarine_block")*/.setCreativeTab(CreativeTabsManager.tabBlock);
    	citrineBlock = new CitrineBlock(Material.iron).setBlockName("citrineBlock")/*.setBlockTextureName(StringLibrary.MODID + ":citrine_block")*/.setCreativeTab(CreativeTabsManager.tabBlock);
    	cobaltBlock = new CobaltBlock(Material.iron).setBlockName("cobaltBlock")/*.setBlockTextureName(StringLibrary.MODID + ":cobalt_block")*/.setCreativeTab(CreativeTabsManager.tabBlock);
    	fireopalCrystalBlock = new FireopalBlock(Material.iron).setBlockName("fireopalCrystalBlock")/*.setBlockTextureName(StringLibrary.MODID + ":fireopalCrystal_block")*/.setCreativeTab(CreativeTabsManager.tabBlock);
    	jetBlock = new JetBlock(Material.iron).setBlockName("jetBlock")/*.setBlockTextureName(StringLibrary.MODID + ":jet_block")*/.setCreativeTab(CreativeTabsManager.tabBlock);
    	peridonBlock = new PeridonBlock(Material.iron).setBlockName("peridonBlock")/*.setBlockTextureName(StringLibrary.MODID + ":peridon_block")*/.setCreativeTab(CreativeTabsManager.tabBlock);
    	roseQuartzBlock = new RoseCrystalBlock(Material.iron).setBlockName("roseQuartzBlock")/*.setBlockTextureName(StringLibrary.MODID + ":roseQuartz_block")*/.setCreativeTab(CreativeTabsManager.tabBlock);
    	sapphireBlock = new SapphireBlock(Material.iron).setBlockName("sapphireBlock")/*.setBlockTextureName(StringLibrary.MODID + ":sapphire_block")*/.setCreativeTab(CreativeTabsManager.tabBlock);
    	siamBlock = new SiamBlock(Material.iron).setBlockName("siamBlock")/*.setBlockTextureName(StringLibrary.MODID + ":siam_block")*/.setCreativeTab(CreativeTabsManager.tabBlock);
    	topazBlock = new TopazBlock(Material.iron).setBlockName("topazBlock")/*.setBlockTextureName(StringLibrary.MODID + ":topaz_block")*/.setCreativeTab(CreativeTabsManager.tabBlock);
        customBlock = new CustomBlock(Material.rock);
        //overworldRoseQuarts = new OverworldRoseQuartz(Material.rock).setBlockTextureName(StringLibrary.MODID + ":overworld_rose");
        //testPortal = new TestPortal();
        blockLeaf = new NCLeaf().setBlockName("Leaf").setCreativeTab(CreativeTabsManager.tabBlock);
        blockLog = new NCLog().setBlockName("Cherry Log").setCreativeTab(CreativeTabsManager.tabBlock);
        sapphireChest = new sapphireChest(0).setBlockName("Sapphire Chest").setCreativeTab(CreativeTabsManager.tabBlock);
        multiBlock = new MultiBlock(Material.rock);
        blockAlabasterOvenIdle = new AlabasterOven(false).setBlockName("AlabasterOvenIdle").setCreativeTab(CreativeTabsManager.tabBlock).setHardness(3.5F);
		blockAlabasterOvenActive = new AlabasterOven(true).setBlockName("AlabasterOvenActive").setLightLevel(0.625F).setHardness(3.5F);
        //customFarmland = new custom_farmland(Material.ice);
        customBlockCrops = new CustomBlockCrops().setBlockName("CustomBlockCrops");//.setBlockTextureName(StringLibrary.MODID + ":custom_block_crops");
        
    }
    //ItemStack gemLapisGem = new ItemStack(Items.dye, 1, 4);
    public static void registerBlock() {
        GameRegistry.registerBlock(customBlock, customBlock.getUnlocalizedName());
        GameRegistry.registerBlock(amethystBlock, amethystBlock.getUnlocalizedName());
        GameRegistry.registerBlock(aquamarineBlock, aquamarineBlock.getUnlocalizedName());
        GameRegistry.registerBlock(citrineBlock, citrineBlock.getUnlocalizedName());
        GameRegistry.registerBlock(fireopalCrystalBlock, fireopalCrystalBlock.getUnlocalizedName());
        GameRegistry.registerBlock(cobaltBlock, cobaltBlock.getUnlocalizedName());
        GameRegistry.registerBlock(jetBlock, jetBlock.getUnlocalizedName());
        GameRegistry.registerBlock(peridonBlock, peridonBlock.getUnlocalizedName());
        GameRegistry.registerBlock(roseQuartzBlock, roseQuartzBlock.getUnlocalizedName());
        GameRegistry.registerBlock(sapphireBlock, sapphireBlock.getUnlocalizedName());
        GameRegistry.registerBlock(siamBlock, siamBlock.getUnlocalizedName());
        GameRegistry.registerBlock(topazBlock, topazBlock.getUnlocalizedName());
        GameRegistry.registerBlock(rubyBlock, rubyBlock.getUnlocalizedName());
        //GameRegistry.registerBlock(sapphireChest, "sapphireChest");
        //GameRegistry.registerBlock(testPortal, "testPortal");
        GameRegistry.registerBlock(blockAlabasterOvenIdle, "AlabasterOvenIdle");
		GameRegistry.registerBlock(blockAlabasterOvenActive, "AlabasterOvenActive");
        GameRegistry.registerBlock(blockLog, ItemLogBlocks.class, blockLog.getUnlocalizedName().substring(5));
        GameRegistry.registerBlock(blockLeaf, ItemLeafBlocks.class, blockLeaf.getUnlocalizedName().substring(5));//.setBlockTextureName(StringLibrary.MODID + ":" +"LeafCherry");
        GameRegistry.registerBlock(endCoal = new EndCoal("endCoal", Material.rock, Items.coal, 2, 4).setHardness(10.0f).setResistance(20.0f), "endCoal");
        GameRegistry.registerBlock(endDiamond = new EndDiamond("endDiamond", Material.rock, Items.diamond, 2, 4).setHardness(10.0f).setResistance(20.0f), "endDiamond");
        GameRegistry.registerBlock(endEmerald = new EndEmerald("endEmerald", Material.rock, Items.emerald, 2, 4).setHardness(10.0f).setResistance(20.0f), "endEmerald");
        GameRegistry.registerBlock(endGold = new EndGold("endGold", Material.rock, Item.getItemFromBlock(BlockManager.endGold), 2, 4).setHardness(10.0f).setResistance(20.0f), "endGold");
        GameRegistry.registerBlock(endIron = new EndIron("endIron", Material.rock, Item.getItemFromBlock(BlockManager.endIron), 2, 4).setHardness(10.0f).setResistance(20.0f), "endIron");
        ItemStack gemLapisGem = new ItemStack(Items.dye, 1, 4);
        GameRegistry.registerBlock(endLapis = new EndLapis("endLapis", Material.rock, gemLapisGem, 2, 4).setHardness(10.0f).setResistance(20.0f), "endLapis");
        GameRegistry.registerBlock(endRedstone = new EndRedstone("endRedstone", Material.rock, Items.redstone, 2, 4).setHardness(10.0f).setResistance(20.0f), "endRedstone");
        GameRegistry.registerBlock(endRuby = new EndRuby("endRuby", Material.rock, ItemManager.tutorial_item, 2, 4).setHardness(10.0f).setResistance(20.0f), "endRuby");
        GameRegistry.registerBlock(endAmethyst = new EndAmethyst("endAmethyst", Material.rock, ItemManager.amethystGem, 2, 4).setHardness(10.0f).setResistance(20.0f), "endAmethyst");
        GameRegistry.registerBlock(endAquamarine = new EndAquamarine("endAquamarine", Material.rock, ItemManager.aquamarineGem, 2, 4).setHardness(10.0f).setResistance(20.0f), "endAquamarine");
        GameRegistry.registerBlock(endCitrine = new EndCitrine("endCitrine", Material.rock, ItemManager.citrineGem, 2, 4).setHardness(10.0f).setResistance(20.0f), "endCitrine");
        GameRegistry.registerBlock(endCobalt = new EndCobalt("endCobalt", Material.rock, ItemManager.cobaltGem, 2, 4).setHardness(10.0f).setResistance(20.0f), "endCobalt");
        GameRegistry.registerBlock(endFireopalCrystal = new EndFireopalCrystal("endFireopalCrystal", Material.rock, ItemManager.fireopalCrystal, 2, 4).setHardness(10.0f).setResistance(20.0f), "endFireopalCrystal");
        GameRegistry.registerBlock(endJet = new EndJet("endJet", Material.rock, ItemManager.jetGem, 2, 4).setHardness(10.0f).setResistance(20.0f), "endJet");
        GameRegistry.registerBlock(endPeridon = new EndPeridon("endPeridon", Material.rock, ItemManager.peridonGem, 2, 4).setHardness(10.0f).setResistance(20.0f), "endPeridon");
        GameRegistry.registerBlock(endRoseQuartz = new EndRoseCrystal("endRoseQuartz", Material.rock, ItemManager.roseCrystal, 2, 4).setHardness(10.0f).setResistance(20.0f), "endRoseQuartz");
        GameRegistry.registerBlock(endSapphire = new EndSapphire("endSapphire", Material.rock, ItemManager.sapphireGem, 2, 4).setHardness(10.0f).setResistance(20.0f), "endSapphire");
        GameRegistry.registerBlock(endSiam = new EndSiam("endSiam", Material.rock, ItemManager.siamGem, 2, 4).setHardness(10.0f).setResistance(20.0f), "endSiam");
        GameRegistry.registerBlock(endTopaz = new EndTopaz("endTopaz", Material.rock, ItemManager.topazGem, 2, 4).setHardness(10.0f).setResistance(20.0f), "endTopaz");
        GameRegistry.registerBlock(endQuartz = new EndQuartz("endQuartz", Material.rock, Items.quartz, 2, 4).setHardness(10.0f).setResistance(20.0f), "endQuartz");
        GameRegistry.registerBlock(netherCoal = new NetherCoal("netherCoal", Material.rock, Items.coal, 2, 4).setHardness(10.0f).setResistance(20.0f), "netherCoal");
        GameRegistry.registerBlock(netherDiamond = new NetherDiamond("netherDiamond", Material.rock, Items.diamond, 2, 4).setHardness(10.0f).setResistance(20.0f), "netherDiamond");
        GameRegistry.registerBlock(netherEmerald = new NetherEmerald("netherEmerald", Material.rock, Items.emerald, 2, 4).setHardness(10.0f).setResistance(20.0f), "netherEmerald");
        GameRegistry.registerBlock(netherGold = new NetherGold("netherGold", Material.rock, Item.getItemFromBlock(BlockManager.netherGold), 2, 4).setHardness(10.0f).setResistance(20.0f), "netherGold");
        GameRegistry.registerBlock(netherIron = new NetherIron("netherIron", Material.rock, Item.getItemFromBlock(BlockManager.netherIron), 2, 4).setHardness(10.0f).setResistance(20.0f), "netherIron");
        GameRegistry.registerBlock(netherLapis = new NetherLapis("netherLapis", Material.rock, gemLapisGem, 2, 4).setHardness(10.0f).setResistance(20.0f), "netherLapis");
        GameRegistry.registerBlock(netherRedstone = new NetherRedstone("netherRedstone", Material.rock, Items.redstone, 2, 4).setHardness(10.0f).setResistance(20.0f), "netherRedstone");
        GameRegistry.registerBlock(netherRuby = new NetherRuby("netherRuby", Material.rock, ItemManager.tutorial_item, 2, 4).setHardness(10.0f).setResistance(20.0f), "netherRuby");
        GameRegistry.registerBlock(netherAmethyst = new NetherAmethyst("netherAmethyst", Material.rock, ItemManager.amethystGem, 2, 4).setHardness(10.0f).setResistance(20.0f), "netherAmethyst");
        GameRegistry.registerBlock(netherAquamarine = new NetherAquamarine("netherAquamarine", Material.rock, ItemManager.aquamarineGem, 2, 4).setHardness(10.0f).setResistance(20.0f), "netherAquamarine");
        GameRegistry.registerBlock(netherCitrine = new NetherCitrine("netherCitrine", Material.rock, ItemManager.citrineGem, 2, 4).setHardness(10.0f).setResistance(20.0f), "netherCitrine");
        GameRegistry.registerBlock(netherCobalt = new NetherCobalt("netherCobalt", Material.rock, ItemManager.cobaltGem, 2, 4).setHardness(10.0f).setResistance(20.0f), "netherCobalt");
        GameRegistry.registerBlock(netherFireopalCrystal = new NetherFireopalCrystal("netherFireopalCrystal", Material.rock, ItemManager.fireopalCrystal, 2, 4).setHardness(10.0f).setResistance(20.0f), "netherFireopalCrystal");
        GameRegistry.registerBlock(netherJet = new NetherJet("netherJet", Material.rock, ItemManager.jetGem, 2, 4).setHardness(10.0f).setResistance(20.0f), "netherJet");
        GameRegistry.registerBlock(netherPeridon = new NetherPeridon("netherPeridon", Material.rock, ItemManager.peridonGem, 2, 4).setHardness(10.0f).setResistance(20.0f), "netherPeridon");
        GameRegistry.registerBlock(netherRoseQuartz = new NetherRoseQuartz("netherRoseQuartz", Material.rock, ItemManager.roseCrystal, 2, 4).setHardness(10.0f).setResistance(20.0f), "netherRoseQuartz");
        GameRegistry.registerBlock(netherSapphire = new NetherSapphire("netherSapphire", Material.rock, ItemManager.sapphireGem, 2, 4).setHardness(10.0f).setResistance(20.0f), "netherSapphire");
        GameRegistry.registerBlock(netherSiam = new NetherSiam("netherSiam", Material.rock, ItemManager.siamGem, 2, 4).setHardness(10.0f).setResistance(20.0f), "netherSiam");
        GameRegistry.registerBlock(netherTopaz = new NetherTopaz("netherTopaz", Material.rock, ItemManager.topazGem, 2, 4).setHardness(10.0f).setResistance(20.0f), "netherTopaz");
        GameRegistry.registerBlock(overworldQuartz = new OverworldQuartz("overworldQuartz", Material.rock, Items.quartz, 2, 4).setHardness(10.0f).setResistance(20.0f), "overworldQuartz");
        GameRegistry.registerBlock(tutorial_ore = new ModBlockOre("tutorial_ore", Material.rock, ItemManager.tutorial_item, 2, 4).setHardness(10.0f).setResistance(20.0f), "tutorial_ore");
        GameRegistry.registerBlock(overworldAmethyst = new OverworldAmethyst("overworldAmethyst", Material.rock, ItemManager.amethystGem, 2, 4).setHardness(10.0f).setResistance(20.0f), "overworldAmethyst");
        GameRegistry.registerBlock(overworldAquamarine = new OverworldAquamarine("overworldAquamarine", Material.rock, ItemManager.aquamarineGem, 2, 4).setHardness(10.0f).setResistance(20.0f), "overworldAquamarine");
        GameRegistry.registerBlock(overworldCitrine = new OverworldCitrine("overworldCitrine", Material.rock, ItemManager.citrineGem, 2, 4).setHardness(10.0f).setResistance(20.0f), "overworldCitrine");
        GameRegistry.registerBlock(overworldCobalt = new OverworldCobalt("overworldCobalt", Material.rock, ItemManager.cobaltGem, 2, 4).setHardness(10.0f).setResistance(20.0f), "overworldCobalt");
        GameRegistry.registerBlock(overworldFireopalCrystal = new OverworldFireopalCrystal("overworldFireopalCrystal", Material.rock, ItemManager.fireopalCrystal, 2, 4).setHardness(10.0f).setResistance(20.0f), "overworldFireopalCrystal");
        GameRegistry.registerBlock(overworldJet = new OverworldJet("overworldJet", Material.rock, ItemManager.jetGem, 2, 4).setHardness(10.0f).setResistance(20.0f), "overworldJet");
        GameRegistry.registerBlock(overworldPeridon = new OverworldPeridon("overworldPeridon", Material.rock, ItemManager.peridonGem, 2, 4).setHardness(10.0f).setResistance(20.0f), "overworldPeridon");
        GameRegistry.registerBlock(overworldRoseQuartz = new OverworldRoseQuartz("overworldRoseQuartz", Material.rock, ItemManager.roseCrystal, 2, 4).setHardness(10.0f).setResistance(20.0f), "overworldRoseQuartz");
        GameRegistry.registerBlock(overworldSapphire = new OverworldSapphire("overworldSapphire", Material.rock, ItemManager.sapphireGem, 2, 4).setHardness(10.0f).setResistance(20.0f), "overworldSapphire");
        GameRegistry.registerBlock(overworldSiam = new OverworldSiam("overworldSiam", Material.rock, ItemManager.siamGem, 2, 4).setHardness(10.0f).setResistance(20.0f), "overworldSiam");
        GameRegistry.registerBlock(overworldTopaz = new OverworldTopaz("overworldTopaz", Material.rock, ItemManager.topazGem, 2, 4).setHardness(10.0f).setResistance(20.0f), "overworldTopaz");
        //GameRegistry.registerBlock(tutorial_ore = new ModBlockOre("tutorial_ore", Material.rock, ItemManager.tutorial_item, 2, 4), "tutorial_ore");
        //GameRegistry.registerBlock(customFarmland, customFarmland.getUnlocalizedName());
        GameRegistry.registerBlock(customBlockCrops, customBlockCrops.getUnlocalizedName());
        GameRegistry.registerBlock(multiBlock, multiBlock.getUnlocalizedName());
    }
 
}